#ifndef ERRORS
#define ERRORS
typedef enum ERRORS{
    NULL_PTR_IN_UNEXCITED_PLACE,
    FREEING_OF_NULL_PTR,
    MEMORY_OVERFLOW,
    IT_IS_OK,
    WRONG_INPUT_FROM_STREAM,
    RUNTIME_ERROR,
    NOT_FOUND,
    FILE_WAS_NOT_FOUND,
} Error;
#endif